syntax = "proto3";

package sovereign.config.v3;

import "google/protobuf/timestamp.proto";

service System {
  rpc GetVersion(GetVersionRequest) returns (GetVersionResponse);
  rpc GetIdentity(GetIdentityRequest) returns (GetIdentityResponse);
}

service Configuration {
  rpc ListValues(ListValuesRequest) returns (ListValuesResponse);
  rpc GetSubTree(GetSubTreeRequest) returns (GetSubTreeResponse);
  rpc PutValue(PutValueRequest) returns (PutValueResponse);
  rpc ReplaceSubTree(ReplaceSubTreeRequest) returns (ReplaceSubTreeResponse);
  rpc DeleteValues(DeleteValuesRequest) returns (DeleteValuesResponse);
  rpc RevealSecret(RevealSecretRequest) returns (RevealSecretResponse);
}

enum ValueClassification {
  VALUE_CLASSIFICATION_UNSPECIFIED = 0;
  VALUE_CLASSIFICATION_PLAIN = 1;
  VALUE_CLASSIFICATION_SECRET = 2;
}

message MaskedSecret {}
message PreserveSecret {}

message ListValuesRequest {
  string path = 1;
}

message ListedValue {
  string path = 1;
  oneof content {
    string plain_value = 2;
    MaskedSecret masked_secret = 5;
  }
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
  ValueClassification classification = 6;
}

message ListValuesResponse {
  repeated ListedValue values = 1;
  repeated string paths = 2;
}

message GetSubTreeRequest {
  string path = 1;
}

message SubTreeValue {
  string path = 1;
  oneof content {
    string plain_value = 2;
    MaskedSecret masked_secret = 3;
  }
  ValueClassification classification = 4;
}

message GetSubTreeResponse {
  repeated SubTreeValue values = 1;
}

message PutValueRequest {
  string path = 1;
  oneof content {
    string plain_value = 2;
    string secret_value = 3;
  }
}

message PutValueResponse {
  google.protobuf.Timestamp created_at = 1;
  google.protobuf.Timestamp updated_at = 2;
}

message SubTreeMutationValue {
  string path = 1;
  oneof content {
    string plain_value = 2;
    PreserveSecret preserve_secret = 3;
  }
}

message ReplaceSubTreeRequest {
  string path = 1;
  repeated SubTreeMutationValue values = 2;
}

message ReplaceSubTreeResponse {
  google.protobuf.Timestamp updated_at = 1;
  uint64 value_count = 2;
}

message DeleteValuesRequest {
  string path = 1;
  bool recurse = 2;
}

message DeleteValuesResponse {
  google.protobuf.Timestamp deleted_at = 1;
  uint64 deleted_count = 2;
}

message RevealSecretRequest {
  string path = 1;
}

message RevealSecretResponse {
  string value = 1;
}

message GetIdentityRequest {}

message GetIdentityResponse {
  bool authenticated = 1;
}

message GetVersionRequest {
  string protocol_version = 1;
}

message GetVersionResponse {
  string application_version = 1;
  string protocol_version = 2;
}
