[package]
name = "sovereign-config-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
prost.workspace = true
tonic.workspace = true

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-build = "0.12.3"
