[package]
name = "sovereign-config-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
bytes.workspace = true
getrandom.workspace = true
http.workspace = true
http-body-util.workspace = true
mime_guess.workspace = true
prost-types.workspace = true
reqwest = { workspace = true, features = ["json"] }
rust-embed.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
tonic = { workspace = true, features = ["tls", "transport"] }
tonic-health.workspace = true
tonic-web.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sovereign-config-proto = { path = "../sovereign-config-proto" }
sovereign-config-core = { path = "../sovereign-config-core" }

[dev-dependencies]
serde_yaml.workspace = true
tempfile = "3.27.0"

[lints]
workspace = true
