syntax = "proto3";

package sovereign.config.v1;

import "google/protobuf/timestamp.proto";

service System {
  rpc GetVersion(GetVersionRequest) returns (GetVersionResponse);
  rpc GetIdentity(GetIdentityRequest) returns (GetIdentityResponse);
}

service Configuration {
  rpc ListValues(ListValuesRequest) returns (ListValuesResponse);
  rpc GetValue(GetValueRequest) returns (GetValueResponse);
  rpc PutValue(PutValueRequest) returns (PutValueResponse);
  rpc DeleteValue(DeleteValueRequest) returns (DeleteValueResponse);
}

message ListValuesRequest {
  string path = 1;
}

message ListedValue {
  string path = 1;
  string value = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
}

message ListValuesResponse {
  repeated ListedValue values = 1;
  repeated string paths = 2;
}

message GetValueRequest {
  string path = 1;
}

message GetValueResponse {
  string value = 1;
  google.protobuf.Timestamp created_at = 2;
  google.protobuf.Timestamp updated_at = 3;
}

message PutValueRequest {
  string path = 1;
  string value = 2;
}

message PutValueResponse {
  google.protobuf.Timestamp created_at = 1;
  google.protobuf.Timestamp updated_at = 2;
}

message DeleteValueRequest {
  string path = 1;
}

message DeleteValueResponse {
  google.protobuf.Timestamp deleted_at = 1;
}

message GetIdentityRequest {}

message GetIdentityResponse {
  bool authenticated = 1;
}

message GetVersionRequest {
  string protocol_version = 1;
}

message GetVersionResponse {
  string application_version = 1;
  string protocol_version = 2;
}
